sudo: required

services:
  - docker

before_install:
  - docker build -t dockertest/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true dockertest/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-ap-southeast-1-691488653072 
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET